query user($login: String!) {
  user(login: $login) {
    login
    avatarUrl
    name
    bio
    followers {
      totalCount
    }
    following {
      totalCount
    }
    repositories(first: 100) {
      nodes {
        id
        name
        description
        stargazers {
          totalCount
        }
        parent {
          url
        }
        forkCount
        isFork
        primaryLanguage {
          name
        }
      }
    }
  }
}
